name: marinode
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  connectivity_plus: ^6.1.0
  file_picker: ^8.1.4
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
